all: \
	modernC/11/ex9 \
	CPAMA/11/ex06 \
	modernC/11/ex14 \
	modernC/11/ex15 \
	modernC/11/ex16 \
	modernC/11/ch12 \
	figures/use-fptr \
	modernC/11/ch13 \
	modernC/12/ex25 # includes 23, 24

CFLAGS = -g -Og -Wall -Wextra -pedantic --std=c11

.SUFFIXES: .c
.PHONY: all

modernC/11/ch13: LDFLAGS=-lm
